### ISSUE TITLE
tsv files and final heatmap

### ISSUE THREAD

**Issue by samantneha** [FowlerLab/Enrich2#25]
Hello, I am attempting to use Enrich2 for enrichment/depletion ration of WT, Syn and variants between input(i call it sample 10) and test sample  (sample 1). I use the GUI and specify input and sample, Wt sequence, mutations allowed = 3 (I have NNN library), protein coding. 
In the output tsv folder I get two folders, 
1.filename_lib 
2. filename_sel 
In both I get 
1. main_variant_counts for sample 1
2. main_variant_counts for sample 10
3. main_variant_counts for comparison sample 10 to 1
4. main_synonymous_counts for sample 1
5. main_synonymous_counts for sample 10 
6. main_synonymous_counts for comparison sample 10 to 1

I have to manually filter out more than 3 mutations in a codon at a time, this is what I get (attachment, tsv data and Relative abundance).

I want to understand how the synonyms are counted, because if I take relative abundance between input and sample, the WT is depleted and synonyms are enriched. (I expect WT and synonyms to show same behavior, equally enriched/depleted) (find in attachment sheet#2), 

Also, what does (p.=) and p.Val2??? mean.  Do I analyse main_variant_counts or main_synonymous_counts? What is the difference between the two files? 

The heatmap (attached), shows that the WT are light blue (depleted), I assume they should be heavily depleted. Does the heatmap combine WT and synonyms together? 
Thanks

[sequence_function_map_aa.pdf](https://github.com/FowlerLab/Enrich2/files/3060490/sequence_function_map_aa.pdf)

[Enrich2_data.xlsx](https://github.com/FowlerLab/Enrich2/files/3060488/Enrich2_data.xlsx)

**Comment by afrubin** [comment]
Wild type can appear depleted because there are many higher-fitness variants in the sample. Synonymous variants are not visualized in this sequence function map.

The difference between `variant` and `synonymous` is explained [in the documentation](https://enrich2.readthedocs.io/en/latest/introduction.html#elements).

`(p.=)` means that there was a nucleotide change but no amino acid change. `p.Val2???` means that there was an untranslatable mutation affecting the valine at amino acid position 2 (untranslatable because of an N base or truncation).

I'm afraid I can't comment on why you have a difference between the `_sy` and `_wt` variants because I don't understand the experimental design, but hopefully this reply answers most of your questions. You could try looking at the synonymous variants to see if there are any outliers driving the difference.

**Comment by samantneha** [comment]
Hi Alan,

I am very glad to get your response. Also I am the same person from UMass
med school Bolon Lab you replied to, I just posted on github to see if
thats a better way to get in touch with the authors, sorry about having it
posted as well as emailed.)

If you have some time to spare I would really appreciate help on the data
analysis.

Experimental setup:
1.Express Substrate library on yeast surface with two tags add Enzyme to
observe substrate cleavage
2. Analyze substrate library using deep sequencing
3. I want to compare Input (No enzyme treatment) with each window of enzyme
treatment. (Window 1 = Orange cells, Window 2=  green cells, window 3 =
blue cells).
4. So in GUI I do 1 by 1 comparison, I put Input as time point 0, and one
window (orange cells) as time point 1. WT = Wt sequence of the substrate.
Normalize to Library size (complete case)? I am not sure what I should
normalize to?

And I want to know what is the enrichment/depletion  ratio of Wt and
variants between input and sample. Kindly see the images below for better
representation of the experiment.
The heat map below shows comparisons with input and all the three windows,
but in the excel sheet attached I have manually sorted single mutations and
relative abundance, as well as normalized relative abundance (i.e. Relative
Abundance/wt) between input and window 1. It seems like some variants show
double the abundance than the Wt, is that why I see Wt in the heat map to
be constantly in blue range in all of the three windows?

Does the heat map only plot Wt and the variants, and would filter out >20
Phred score, more than 3 consecutive nt mutations (i.e. only single amino
acid change per read).

If you could kindly see the attached excel sheet I have highlighted the wt
and synonyms and their Rel abundance, it looks like the counts do not match
between input and window 1
In the input #syn/wt = 1.5, window 1 = #syn/wt = 2.3, which is why
according to the relative abundance, Wt = 1, while Syn = 1.4

Also can you please go over the heat map once again please, I don't
entirely understand what its plotting, only Wt and variants? or wt+synonyms
and variants?

I really appreciate all your help, and I would be happy to answer all
questions or queries about the experimental setup, the experimental setup
is clear my head but I can imagine to go through someone else's experiment
and data analysis would be difficult to follow, so please let me know if
anything is not clear and I will do my best to rephrase it.

Again, thanks a ton

Best,
Neha

[image: image.png][image: image.png]
[image: image.png]

**Comment by afrubin** [comment]
It doesn't look like the images attached correctly, but since this is a design question rather than a software question it would be better to discuss it over email rather than in this GitHub issue. Please reply to that email thread (with attachments if you like) when you are ready and I'll try to help.
