### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by FPonath** [FowlerLab/Enrich2#30]
Hello,

I was wondering if it is possible when running Enrich2 on a server to make use of multithreading to speed the analysis/alignment along?

Best regards,
Falk

**Comment by afrubin** [comment]
Enrich2 doesn't support multiple threads, but there is a somewhat clumsy workaround.

Since most processing time is spent counting reads, you can create a separate config file for each sequencing library and launch those on a server in parallel.

Once the counting is done, run Enrich2 using the full config file, which will calculate scores using the existing counts (assuming the file paths are consistent between config files).

Hope this helps!
