### ISSUE TITLE
Failed to save config file or accept zero time-points

### ISSUE THREAD

**Issue by shesanIsland** [FowlerLab/Enrich2#61]
Hello, 

Thank you for the DMS analysis tool. I have a few questions as I am unsure what is causing my issues. I have been given a pilot experiment where 5 samples from a single selection where the paired-end reads have been merged to form a single ._fastq_ file.

- aim: identify single or double protein variants within a protein from DMS
- config includes: `experiment` as root object, 1 condition, 1 selection, 5 fastq files as basic , WT 0 time points, WT sequence as DNA, use aligner
- error message 1 when trying to save configuration: "`Failed to save config file.`"
- error message 2 when trying to run analysis: "`Multiple timepoints required [Selection 1]`" (see screenshot below)

I am bit confused here as the example .JSON file also has zero timepoints. Any advised would be appreciated.

Thanks

<img width="721" alt="image" src="https://github.com/FowlerLab/Enrich2/assets/74415379/3bf7912d-6ce4-435d-b7cc-8dc89d10e14b">

**Comment by afrubin** [comment]
@shesanIsland Thanks for using Enrich2, and sorry for the delay in replying to this issue.

It sounds like you might be running into problems because the program is expecting multiple time points that it can use to calculate a score.

Instead, it sounds like you are trying to use the program to identify/count variants. Try using the "Counts Only" mode on the right side and see if you can count one of your FASTQ files as a test.

Also, I don't recommend the "User Aligner" option. It's very slow and experimental and seems to be the source of crashes for many users.

**Comment by shesanIsland** [comment]
@afrubin Thank you very much for your response!

Yes we are attempting to count the number of single/double mutations within samples and subsequently calculate positional enrichment from the unselected/selected DMS data when compared to the WT. 

Following your suggestion, I was able to use the 'Counts Only' option (and also 'Log Ratios') where I initially bypassed the time-point issue but ran into this error:
<img width="313" alt="image" src="https://github.com/FowlerLab/Enrich2/assets/74415379/2faca478-63c4-424e-908f-d4136d3cae7f">

After closing and re-opening the GUI to try again, I ran into the same time-point error again. At this point we'll continue to look into this, plus other tools.

Many thanks
